<a href="https://colab.research.google.com/github/ambulesubhada07/Data_Science_pandas/blob/main/pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **load dataset**

In [1]:
import pandas as pd

In [2]:
# from github: .csv .txt .tsv .data
import pandas as pd

f = pd.read_csv('https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/fifa_eda.csv')
f.head(2)  # check first 2 records

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0

In [3]:
f.tail(3) # last 3 records

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [4]:
f.sample(3)  # randomly select any 3 records

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
17808,245123,A. Mahlonoko,16,South Africa,52,71,Orlando Pirates,100.0,1.0,Right,1.0,2.0,CAM,2018,2020-01-01,5.666667,130.0,278.0
11927,207584,M. Boman,29,Sweden,64,64,Randers FC,450.0,4.0,Right,1.0,2.0,ST,2018,2019-01-01,6.166667,203.0,563.0
7415,190408,M. Reginiussen,30,Norway,68,68,Ranheim Fotball,825.0,2.0,Right,1.0,3.0,LCM,2012,2019-01-01,5.750000,154.0,1000.0

In [6]:
# download any excel csv txt file from github
# link: https://github.com/prasertcbs/basic-dataset/tree/master/Tokyo2020
dt = pd.read_excel('/content/Olympic2020_medal.xlsx')
dt.head(2)

                         Team  NOC  Gold  Silver  Bronze  Total
0    United States of America  USA    39      41      33    113
1  People's Republic of China  CHN    38      32      18     88

# **Perform Initial Operations**

In [7]:
# summary of dataset info()
f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

In [8]:
f.shape

(18207, 18)

In [9]:
# check column names
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [11]:
f['Preferred Foot']

0         Left
1        Right
2        Right
3        Right
4        Right
         ...
18202    Right
18203    Right
18204    Right
18205    Right
18206    Right
Name: Preferred Foot, Length: 18207, dtype: object

In [12]:
# check statistical summary of data
f.describe().T # will be applied on Numeric data

,count,mean,std,min,25%,50%,75%,max
ID,18207.0,214298.338606,29965.244204,16.000000,200315.50,221759.000000,236529.500000,246620.00
Age,18207.0,25.122206,4.669943,16.000000,21.00,25.000000,28.000000,45.00
Overall,18207.0,66.238699,6.908930,46.000000,62.00,66.000000,71.000000,94.00
Potential,18207.0,71.307299,6.136496,48.000000,67.00,71.000000,75.000000,95.00
Value,17955.0,2444.530214,5626.715434,10.000000,325.00,700.000000,2100.000000,118500.00
Wage,18207.0,9.731312,21.999290,0.000000,1.00,3.000000,9.000000,565.00
International Reputation,18159.0,1.113222,0.394031,1.000000,1.00,1.000000,1.000000,5.00
Skill Moves,18159.0,2.361308,0.756164,1.000000,2.00,2.000000,3.000000,5.00
Joined,18207.0,2016.420607,2.018194,1991.000000,2016.00,2017.000000,2018.000000,2018.00
Height,18207.0,5.946771,0.220514,5.083333,5.75,5.916667,6.083333,6.75
Weight,18207.0,165.979129,15.572775,110.000000,154.00,165.000000,176.000000,243.00
Release Clause,18207.0,4585.060971,10630.414430,13.000000,570.00,1300.000000,4585.060806,228100.00

In [13]:
f.describe().style.background_gradient('Spectral')

In [14]:
# describe on categorical data
f.describe(include='object').T

                      count unique           top   freq
Name                  18207  17194  J. Rodríguez     11
Nationality           18207    164       England   1662
Club                  17966    651      RC Celta     33
Preferred Foot        18207      2         Right  13996
Position              18207     27            ST   2154
Contract Valid Until  17918     35    2019-01-01   4870

In [17]:
f['Preferred Foot'].value_counts()

Preferred Foot
Right    13996
Left      4211
Name: count, dtype: int64

In [19]:
f['Position'].value_counts()

Position
ST     2154
GK     2027
CB     1779
CM     1395
LB     1372
RB     1291
RM     1127
LM     1095
CAM     959
CDM     948
RCB     662
LCB     648
LCM     395
RCM     391
LW      381
RW      370
RDM     248
LDM     243
LS      207
RS      203
RWB      87
LWB      78
CF       74
LAM      21
RAM      21
RF       16
LF       15
Name: count, dtype: int64

In [15]:
# display/check data types of all columns
f.dtypes

ID                            int64
Name                         object
Age                           int64
Nationality                  object
Overall                       int64
Potential                     int64
Club                         object
Value                       float64
Wage                        float64
Preferred Foot               object
International Reputation    float64
Skill Moves                 float64
Position                     object
Joined                        int64
Contract Valid Until         object
Height                      float64
Weight                      float64
Release Clause              float64
dtype: object

In [16]:
# select columns with numeric data type
f.select_dtypes(include='number')  # int float object

,ID,Age,Overall,Potential,Value,Wage,International Reputation,Skill Moves,Joined,Height,Weight,Release Clause
0,158023,31,94,94,110500.0,565.0,5.0,4.0,2004,5.583333,159.0,226500.0
1,20801,33,94,94,77000.0,405.0,5.0,5.0,2018,6.166667,183.0,127100.0
2,190871,26,92,93,118500.0,290.0,5.0,5.0,2017,5.750000,150.0,228100.0
3,193080,27,91,93,72000.0,260.0,4.0,1.0,2011,6.333333,168.0,138600.0
4,192985,27,91,92,102000.0,355.0,4.0,4.0,2015,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,19,47,65,60.0,1.0,1.0,2.0,2017,5.750000,134.0,143.0
18203,243165,19,47,63,60.0,1.0,1.0,2.0,2018,6.250000,170.0,113.0
18204,241638,16,47,67,60.0,1.0,1.0,2.0,2017,5.666667,148.0,165.0
18205,246268,17,47,66,60.0,1.0,1.0,2.0,2018,5.833333,154.0,143.0
18206,246269,16,46,66,60.0,1.0,1.0,2.0,2018,5.833333,176.0,165.0

In [20]:
# rename the column name
# rename Contract Valid Until to Contract
#f.rename({0:'A'})  # default it rename row at the place of 0 --> 'A'
f.rename(columns={'Contract Valid Until':'Contract'},inplace=True) # inplace will make the permnt chnages

In [21]:
# check updated name
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract', 'Height', 'Weight',
       'Release Clause'],
      dtype='object')

In [22]:
f.rename({0:'A'})

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract,Height,Weight,Release Clause
A,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [ ]:
# Assignment: rename below columns
# Preferred Foot--> Preferred_Foot
# International Reputation --> International_Reputation
# Release Clause--> Release_Clause

In [23]:
col = f.columns
print([c.replace(' ','_') for c in col])
# replace directly in columns
f.columns = [c.replace(' ','_') for c in col] #list comprehance

['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club', 'Value', 'Wage', 'Preferred_Foot', 'International_Reputation', 'Skill_Moves', 'Position', 'Joined', 'Contract', 'Height', 'Weight', 'Release_Clause']

In [24]:
f.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred_Foot', 'International_Reputation',
       'Skill_Moves', 'Position', 'Joined', 'Contract', 'Height', 'Weight',
       'Release_Clause'],
      dtype='object')

In [25]:
# create a dataframe with number data in str
k = ['34000','50000','70000']
sal = pd.DataFrame(k,columns=['salary'])
sal

  salary
0  34000
1  50000
2  70000

In [26]:
sal.dtypes

salary    object
dtype: object

In [27]:
#convert salary column data type to float
sal['salary'] = sal['salary'].astype('float32')

In [28]:
sal

    salary
0  34000.0
1  50000.0
2  70000.0

# **Start performing some analysis**